# ==========================================================
# Deadlock Movement Tracker — User Configuration
# ==========================================================
# Notes:
#   - Lines starting with `#` are comments that wont do anything.
#     You can add your own to explain things if you want.

#   - If you change what is in the [brackets] or before the `=`,
#     everything will be broken and explode.

#   - Adjust the value after the `=` to change a setting.
#     Swap true/false for enable/disable.

#   - The key names are case-insensitive

#   - The keys use AutoHotkey syntax (shift = +, ctrl = ^, alt = !)
#     example: Ctrl+Alt+T = ^!t
#     Careful though, u cannot use modifier binds for the deadlock_hotkeys:
#     the valve console doesn't support it. For the tracker_hotkeys it works fine.

#   - Any key bound here cannot be used for any game mechanics

#   - Generally a good idea to copy the file as backup first before editing the values :)
# ==========================================================

[deadlock]
# Path to your Deadlock install directory.
# Change only if you installed it elsewhere than the Steam default.
root=C:\Program Files (x86)\Steam\steamapps\common\Deadlock

[deadlock_hotkeys]
# === Keys meant to be used by player in game too ===

# Toggle noclip on/off (it's also used to reset velocity)
# You can either use your usual noclip key or set a separate one here, not gonna cause problems.
noclip=u

# Enable fast stamina
enable_fast_stamina=k

# Disable fast stamina
disable_fast_stamina=l

# Load practice map while in queue
load_practice_map=8

# Swap teams, once in practice map
swap_team=9

# Enable all cheats, once in practice map
setup_practice=0

# === Keys normally not meant to be used by the player, but could be useful ===

# Accelerate time scale (by a lot !!)
set_host_timescale_fast=,

# Reset time scale to normal (x1)
set_host_timescale_normal=.

# === Keys meant only for the tracker script to send to the game ===

# Best to use virtual keys
mvtrack_mark_pos=F13
mvtrack_teleport=F14
mvtrack_teleport_temp=F15
mvtrack_set_timescale=F16

[tracker_hotkeys]
# Save temporary position, useful to practice quick spots without saving
mark_temp_pos=`

# Teleport to temp saved position
temp_pos_teleport=h

# Mark last attempt as failed and reset position
fail=F1

# Mark last attempt as successful and reset position
success=F2

# Open instance picker to teleport to selected start
switch=F3

# Save current position as a new instance
new=F4

# Undo the last success/fail entry
forget=F5

# Rename the current instance
rename=F6

# Move the instance to our new current position
reposition=F7

# Delete the current instance and its history
delete=F8

# Add a variation to the current instance. The idea is to keep same starting
# position and general destination, but with a different route.
new_variation=F9

# Switch to an existing variation of the current instance.
switch_variation=F10

# Show a graph of your progress for the current instance. (Requires python)
graph=F11

# Close the movement tracker
exit=F12

# Flush the debug logs
flush_logs=^!F12

# Increase/decrease the gamespeed (host_timescale). Mainly for practicing
# difficult moves at lower speed, by 0.05:
inc_host_timescale=!Up
dec_host_timescale=!Down
# by 0.1:
inc_host_timescale_big=^!Up
dec_host_timescale_big=^!Down

# Reset to normal timescale (x1)
norm_host_timescale=!Left

[tracker_settings]
# Show a popup when reaching this many successes in a row. Set to 0 to disable.
target_success_streak=3

# Practice routes without infinite stamina, but still regen instantly between attempts.
# Keep in mind that this setting uses host_timescale to speed up the game which
# can maybe cause some lesser known visual/physics glitches in the game.
use_regular_stamina=true

# Same idea: reset abilities cd on resets, but no infinite cooldowns.
use_regular_cooldowns=true

# How long does it take the script to teleport you to a location, in ms. A
# lower value is faster, but could cause some unpleasant lag on lower end PCs.
# RECOMMENDED MAX: 1000, RECOMMENDED MIN: 20
reset_position_duration=20

# Randomize teleport position on each reset. To avoid "fake improvement" caused
# by over fitted muscle memory over repetitive tries
randomize_reset_pos=true

# Amount of random offset in units applied to X and Y (± value), if the settings
# is enabled. RECOMMENDED min: 20, RECOMMENDED MAX: 60.
randomize_reset_units=40

# If an instance name starts with any of these prefixes, do not apply a randomized
# offset. Useful for practicing routes which are part of a challenge with a
# defined start (example: ROTW for route of the week from the deadlock movement
# discord) or for precise starts close to a ledge.
# examples: `ROTW 25 jan 2026` `norand_edgeboost-route` `SUPERBABANALOLKAWAIIDESU: FAST ROUTE`
# ... add/remove as many as you want. They are case insensitive.
no_randomize_prefixes=norandom, norand, ROTW, randoff, SUPERBABANALOLKAWAIIDESU

# Deadlock four movement keys (they are blocked during teleports to avoid messy movement).
# Comma separated.
movement_keys=w,a,s,d

[dev]
# Set logging level (logs/debug.log). As the script is still in early
# development, everybody's got debug logs, aight ?
logging_level=debug

